### ISSUE TITLE
Elune.sentry Not work

### ISSUE THREAD

**Issue by yuessir** [aevitas/elune.sentry#1]
I follow the instructions but not work in my web api project.
   [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            var foo = Convert.ToInt32("a");//Will throw error but nothing happened in the Sentry portal
            return foo.ToString();
        }
Am I loss something?

Which version of ASP.NET Core are you using?
.Net core 2.1
What's the exception you're getting?
Should get an unhandled exception on the sentry site.

**Comment by aevitas** [comment]
Thanks for your feedback! Can you provide some more details, so I can pinpoint the reason it's not working for you:

- Which version of ASP.NET Core are you using?
- What's the exception you're getting?

As a small side note, Elune.Sentry expects the (now) legacy DSN, marked as `DSN (Deprecated)` in Sentry to function. I'll look into updating the code to use Sentry's own AspNetCore library which should remove this limitation.

Thank you.

**Comment by yuessir** [comment]
It seems to work now :)
